/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Capa_Vista;

import Capa_Conexion.Conexion;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author boris
 */
public class Vista_Solicitar_Insumo extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Solicitar_Insumo
     */
    Conexion cn = new Conexion();
    Connection cc = cn.conexion;

    public Vista_Solicitar_Insumo() {
        initComponents();
        mostrarTabla();
        mostrarTablaSolicitud();
        setTitle("Solicitar Insumos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInsumos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        btnRealizarSoli = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSolicitud = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblInsumos);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnRealizarSoli.setText("Realizar Solicitud");
        btnRealizarSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarSoliActionPerformed(evt);
            }
        });

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Insumos");

        tblSolicitud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSolicitud);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Solicitud");

        jLabel3.setText("Cantidad");

        btnCancelar.setText("Cancelar Solicitud");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnRealizarSoli, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAgregar)
                                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRealizarSoli)
                    .addComponent(btnAtras)
                    .addComponent(btnCancelar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("MEDIDA");
        tblInsumos.setModel(modelo);

        String sql = "";
        sql = "select i.id_insumos, i.nombre, s.cantidad, tp.descripcion from insumos i inner join stock_insumos s on i.id_insumos = s.id_insumos inner join tipo_medida tp on tp.id_tipo_medida = i.id_tipo_medida order by id_insumos asc;";
        String [] dato = new String[4];
        try{
            Statement st = cc.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                dato[0] = rs.getString(1);
                dato[1] = rs.getString(2);
                dato[2] = rs.getString(3);
                dato[3] = rs.getString(4);
                modelo.addRow(dato);
            }
            tblInsumos.setModel(modelo);
        }
        catch(SQLException e){
        }

    }

    public void mostrarTablaSolicitud(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID SOLICITUD");
        modelo.addColumn("ID DETALLE");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("MEDIDA");
        modelo.addColumn("ESTADO");
        tblSolicitud.setModel(modelo);
        String sql = "";
        sql = "select de.id_solicitud_insumo, de.id_detalle, i.nombre, de.cantidad, tp.descripcion, si.estado from solicitud_insumo si inner join detalle_solicitud de on si.id_solicitud_insumo = de.id_solicitud_insumo inner join insumos i on i.id_insumos = de.id_insumo inner join tipo_medida tp on tp.id_tipo_medida = i.id_tipo_medida where si.estado = 'En proceso' order by i.id_insumos asc;";
        String [] dato = new String[6];
        try{
            Statement st = cc.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                dato[0] = rs.getString(1);
                dato[1] = rs.getString(2);
                dato[2] = rs.getString(3);
                dato[3] = rs.getString(4);
                dato[4] = rs.getString(5);
                dato[5] = rs.getString(6);
                modelo.addRow(dato);
            }
            tblSolicitud.setModel(modelo);
        }
        catch(SQLException e){
        }

    }


    public int existeInsumo(int insumo){
        PreparedStatement ps = null;
        ResultSet rs = null;
        String sql = "SELECT COUNT(id_solicitud_insumo) FROM detalle_solicitud WHERE id_insumo = ? and fecha = curdate() and estado = 'En proceso';";
        try{
            ps = cc.prepareStatement(sql);
            ps.setInt(1, insumo);
            rs = ps.executeQuery();
            if(rs.next()){
                return rs.getInt(1);
            }
            return 1;
        }
        catch (SQLException ex){
            return 1;
        }
    }


    private void btnRealizarSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarSoliActionPerformed
        int i = JOptionPane.showConfirmDialog(this,"¿Está seguro de que desea realizar esta Solicitud?","Mensajes", JOptionPane.ERROR_MESSAGE);
        if (i == 0){
            try {
                CallableStatement modificar = cc.prepareCall("{call actualizarSolicitud()}");
                modificar.execute();
                JOptionPane.showMessageDialog(this,"¡Solicitud realizada exitosamente!","Mensajes", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Problemas de conexión con la Base de Datos",
                    "Mensajes", JOptionPane.ERROR_MESSAGE);
            }
        }
        mostrarTablaSolicitud();
                   
    }//GEN-LAST:event_btnRealizarSoliActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String cantidad;
        int capentero;
        int existe;
        cantidad = txtCantidad.getText();
        int fila = tblInsumos.getSelectedRow();
        String valor = tblInsumos.getValueAt(fila, 0).toString();
        int id_insumo = Integer.parseInt(valor);
        //existe = existeInsumo(id_insumo);

        if ((cantidad.equals(""))){
            JOptionPane.showMessageDialog(this, "Debe ingresar una cantidad","Precaución", JOptionPane.WARNING_MESSAGE);
        }
        else{
            int i = JOptionPane.showConfirmDialog(this,"¿Está seguro de que desea agregar este Insumo a la solicitud?","Mensajes", JOptionPane.ERROR_MESSAGE);
            if (i == 0){
                //if (existe == 0){
                    try {
                        capentero =Integer.parseInt(cantidad);
                        CallableStatement insert = cc.prepareCall("{call insertarInsumoSolicitud(?,?)}");
                        insert.setString(1, valor);
                        insert.setInt(2, capentero);
                        insert.execute();
                        JOptionPane.showMessageDialog(this,"¡Insumo agregado exitosamente!","Mensajes", JOptionPane.INFORMATION_MESSAGE);
                        txtCantidad.setText("");
                    }catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Problemas de conexión con la Base de Datos",
                            "Mensajes", JOptionPane.ERROR_MESSAGE);
                    }
                }
               /* else{
                    try {
                        capentero =Integer.parseInt(cantidad);
                        CallableStatement insert = cc.prepareCall("{call insertarInsumoSolicitud(?,?)}");
                        insert.setString(1, valor);
                        insert.setInt(2, capentero);
                        insert.execute();
                        JOptionPane.showMessageDialog(this,"¡Insumo agregado exitosamente!","Mensajes", JOptionPane.INFORMATION_MESSAGE);
                        txtCantidad.setText("");
                    }catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Problemas de conexión con la Base de Datos",
                            "Mensajes", JOptionPane.ERROR_MESSAGE);
                    }*/
                }
        mostrarTablaSolicitud();
        mostrarTabla();                                  
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Vista_Bodega visBod = new Vista_Bodega();
        visBod.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int i = JOptionPane.showConfirmDialog(this,"¿Está seguro de que desea cancelar la Solicitud?","Mensajes", JOptionPane.ERROR_MESSAGE);
        if (i == 0){
            try {
                CallableStatement delete = cc.prepareCall("{call cancelarSolicitud()}");
                delete.execute();
                JOptionPane.showMessageDialog(this,"¡Solicitud cancelada exitosamente!","Mensajes", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Problemas de conexión con la Base de Datos",
                    "Mensajes", JOptionPane.ERROR_MESSAGE);
            }
        }
        mostrarTablaSolicitud();
    }//GEN-LAST:event_btnCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRealizarSoli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblInsumos;
    private javax.swing.JTable tblSolicitud;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
