/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Vista;

import Capa_Conexion.Conexion;
import Capa_Controlador.ControladorCmbPlato;
import Capa_Modelo.Plato;
import Capa_Modelo.TextPrompt;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
/**
 *
 * @author tomas
 */
public class Vista_Crear_Receta extends javax.swing.JFrame {

    ControladorCmbPlato controlador = new ControladorCmbPlato();
    ArrayList ListaPlato;
    Conexion cn = new Conexion();
    Connection cc = cn.conexion;
    public Vista_Crear_Receta() {
        initComponents();
        LlenarCMBPlato();
        TextPrompt placeholder = new TextPrompt("Ingrese el nombre de su receta", txtNombreReceta);
        System.out.println(ListaPlato);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtNombreReceta = new javax.swing.JTextPane();
        btnAtras = new javax.swing.JButton();
        btnCrearReceta = new javax.swing.JButton();
        cmbPlato = new javax.swing.JComboBox<>();
        btnAnadirIngredientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Receta");

        jScrollPane1.setViewportView(txtNombreReceta);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnCrearReceta.setText("Crear Receta");
        btnCrearReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRecetaActionPerformed(evt);
            }
        });

        cmbPlato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPlatoActionPerformed(evt);
            }
        });

        btnAnadirIngredientes.setText("Añadir Ingredientes");
        btnAnadirIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirIngredientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbPlato, 0, 225, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrearReceta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnadirIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearReceta))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnadirIngredientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Vista_Cocina visCo = new Vista_Cocina();
        visCo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnCrearRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRecetaActionPerformed
        String nomReceta = txtNombreReceta.getText();
        if (nomReceta.equals("")){
            JOptionPane.showMessageDialog(this, "La receta debe tener un nombre","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        String nombrePlato;
        String nombreReceta;
        int id = 0;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String sql = "";
        int i = JOptionPane.showConfirmDialog(this,"¿Está seguro de que desea agregar esta Receta?","Mensajes", JOptionPane.ERROR_MESSAGE);
        if (i == 0){
            try {
                nombrePlato = cmbPlato.getSelectedItem().toString();
                nombreReceta = txtNombreReceta.getText();
                sql = "select id from plato Where name = ?;";
                ps = cc.prepareStatement(sql);
                ps.setString(1, nombrePlato);
                rs = ps.executeQuery();
               if (rs.next()){
                    id = Integer.parseInt(rs.getString("id"));
                }
                CallableStatement insert = cc.prepareCall("{call insertarReceta(?,?)}"); 
                insert.setInt(1, id);
                insert.setString(2, nombreReceta);
                insert.execute();
                JOptionPane.showMessageDialog(this,"¡Receta agregada exitosamente!","Mensajes", JOptionPane.INFORMATION_MESSAGE);
                cmbPlato.setSelectedIndex(0);
            } 
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Problemas de conexión con la Base de Datos","Mensajes", JOptionPane.ERROR_MESSAGE);
            }
        }
        }
    }//GEN-LAST:event_btnCrearRecetaActionPerformed

    private void cmbPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPlatoActionPerformed

    private void btnAnadirIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirIngredientesActionPerformed
        Vista_Ingredientes_Receta visIn = new Vista_Ingredientes_Receta();
        visIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAnadirIngredientesActionPerformed

    public void LlenarCMBPlato(){
        try {
            cmbPlato.removeAllItems();
            ListaPlato = controlador.getListaPlato();
            Iterator iter = ListaPlato.iterator();
            while (iter.hasNext()){
                Plato plato= (Plato) iter.next();
                cmbPlato.addItem(plato.toString());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Hubo un error","Aviso",JOptionPane.WARNING_MESSAGE);
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirIngredientes;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCrearReceta;
    private javax.swing.JComboBox<String> cmbPlato;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtNombreReceta;
    // End of variables declaration//GEN-END:variables
}
