/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Vista;

import Capa_Conexion.Conexion;
import Capa_Controlador.ControladorCmbReceta;
import Capa_Controlador.ControladorCmbInsumo;
import Capa_Modelo.Receta;
import Capa_Modelo.Insumo;
import java.sql.CallableStatement;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tomas
 */
public class Vista_Ingredientes_Receta extends javax.swing.JFrame {

    ControladorCmbReceta controlador = new ControladorCmbReceta();
    ControladorCmbInsumo controladorInsumo = new ControladorCmbInsumo();
    ArrayList ListaReceta;
    ArrayList ListaInsumo;
    Conexion cn = new Conexion();
    Connection cc = cn.conexion;
    ResultSet rs;
    PreparedStatement ps = null;
    public Vista_Ingredientes_Receta() {
        initComponents();
        LlenarCMBReceta();
        LlenarCMBInsumos();
        mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngredientes = new javax.swing.JTable();
        cmbInsumos = new javax.swing.JComboBox<>();
        btnAtras = new javax.swing.JButton();
        cmbRecetas = new javax.swing.JComboBox<>();
        btnAgregarIngrediente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblIngredientes);

        cmbInsumos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        cmbRecetas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAgregarIngrediente.setText("Agregar Ingrediente");
        btnAgregarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarIngredienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(cmbInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnAgregarIngrediente)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarIngrediente))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Vista_Crear_Receta visCR = new Vista_Crear_Receta();
        visCR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAgregarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarIngredienteActionPerformed
        String nombreInsumo;
        String nombreReceta;
        int idInsumo = 0;
        int idReceta = 0;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String sql = "";
        int i = JOptionPane.showConfirmDialog(this,"¿Está seguro de que desea agregar esta Receta?","Mensajes", JOptionPane.ERROR_MESSAGE);
        if (i == 0){
            try {
                nombreInsumo = cmbInsumos.getSelectedItem().toString();
                nombreReceta = cmbRecetas.getSelectedItem().toString();
                sql = "SELECT id_insumos from insumos where nombre = ?;";
                ps = cc.prepareStatement(sql);
                ps.setString(1, nombreInsumo);
                rs = ps.executeQuery();
               if (rs.next()){
                    idInsumo = Integer.parseInt(rs.getString("id_insumos"));
                }
                sql = "SELECT id_receta from receta where descripcion = ?;";
                ps = cc.prepareStatement(sql);
                ps.setString(1, nombreReceta);
                rs = ps.executeQuery();
               if (rs.next()){
                    idReceta = Integer.parseInt(rs.getString("id_receta"));
                }
                CallableStatement insert = cc.prepareCall("{call insertarRecetaInsumos(?,?)}"); 
                insert.setInt(1, idReceta);
                insert.setInt(2, idInsumo);
                insert.execute();
                JOptionPane.showMessageDialog(this,"¡Ingrediente agregado exitosamente!","Mensajes", JOptionPane.INFORMATION_MESSAGE);
                cmbInsumos.setSelectedIndex(0);
                cmbRecetas.setSelectedIndex(0);
                mostrarTabla();
            } 
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Problemas de conexión con la Base de Datos","Mensajes", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAgregarIngredienteActionPerformed

    public void LlenarCMBReceta(){
        try {
            cmbRecetas.removeAllItems();
            ListaReceta = controlador.getListaReceta();
            Iterator iter = ListaReceta.iterator();
            while (iter.hasNext()){
                Receta receta = (Receta) iter.next();
                cmbRecetas.addItem(receta.toString());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Hubo un error","Aviso",JOptionPane.WARNING_MESSAGE);
        }
        
    }
    public void LlenarCMBInsumos(){
        try {
            cmbInsumos.removeAllItems();
            ListaInsumo = controladorInsumo.getListaInsumo();
            Iterator iter = ListaInsumo.iterator();
            while (iter.hasNext()){
                Insumo insumo = (Insumo) iter.next();
                cmbInsumos.addItem(insumo.toString());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Hubo un error","Aviso",JOptionPane.WARNING_MESSAGE);
        }
        
    }
    public void mostrarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("RECETA");
        modelo.addColumn("INGREDIENTE");
        tblIngredientes.setModel(modelo);
        String sql = "";
        sql = "SELECT r.descripcion, i.nombre from receta r inner join receta_insumos ri on (r.id_receta = ri.id_receta) inner join insumos i on (i.id_insumos = ri.id_insumos) order by descripcion asc;";
        String [] dato = new String[2];
        try{
            ps = cc.prepareStatement(sql);
            rs = ps.executeQuery();
            while(rs.next()){
                dato[0] = rs.getString(1);
                dato[1] = rs.getString(2);
                modelo.addRow(dato);
            }
            tblIngredientes.setModel(modelo);
        }
        catch(SQLException e){
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarIngrediente;
    private javax.swing.JButton btnAtras;
    private javax.swing.JComboBox<String> cmbInsumos;
    private javax.swing.JComboBox<String> cmbRecetas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIngredientes;
    // End of variables declaration//GEN-END:variables
}
