/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Vista;

import Capa_Conexion.Conexion;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author tomas
 */
public class Vista_Calcular_Ganancias extends javax.swing.JFrame {

    Conexion cc = new Conexion();
    Connection cn = cc.conexion;
    public Vista_Calcular_Ganancias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnGastos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcular Ganancias");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("REPORTES");

        btnCalcular.setText("Ganancias");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnGastos.setText("Gastos");
        btnGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(677, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(btnGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addComponent(btnAtras)
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        Document doc_ganancia = new Document();
        PdfPTable tabla_ganancias = new PdfPTable(3);
        Vista_Emitir_Boleta vis = new Vista_Emitir_Boleta();
        String path = "C:\\Users\\tomas\\Desktop\\ganancias.pdf";
        try {
            String descuento = "";
            PdfWriter.getInstance(doc_ganancia, new FileOutputStream(path));
            doc_ganancia.open();
            PreparedStatement ps = null;
            ResultSet rs = null;
            String sql = "select * from venta v;";
            //descuento = Integer.parseInt(sql1);
            ps = cn.prepareStatement(sql);
            rs = ps.executeQuery();
            tabla_ganancias.addCell("ID");
            tabla_ganancias.addCell("FECHA VENTA");
            tabla_ganancias.addCell("TOTAL VENTA");
            while(rs.next()){
                tabla_ganancias.addCell(rs.getString(1));
                tabla_ganancias.addCell(rs.getString(2));
                tabla_ganancias.addCell(rs.getString(3));
            }
            String sql1 = "select sum(total) from venta v;";
            ps = cn.prepareStatement(sql1);
            rs = ps.executeQuery();
            if(rs.next()){
               descuento = rs.getString("sum(total)"); 
            }
            Phrase nombre_REST = new Phrase("RESTAURANT SIGLO XXI\n\n\n");
            Phrase fecha = new Phrase("Con fecha: " + vis.fechaActual() + "\n\n");
            Phrase descuentos = new Phrase("Total de ventas: " + descuento);
            doc_ganancia.add(nombre_REST);
            doc_ganancia.add(fecha); 
            doc_ganancia.add(tabla_ganancias);
            doc_ganancia.add(descuentos);
            doc_ganancia.close();
            JOptionPane.showMessageDialog(this,"¡Documento generado con éxito!","Aviso",JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(this,"La ruta de su archivo es \n" + path,"Aviso",JOptionPane.INFORMATION_MESSAGE);
        } catch (DocumentException | FileNotFoundException | SQLException e) {
        }
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Vista_Finanzas visFi = new Vista_Finanzas();
        visFi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastosActionPerformed
        Document doc_gastos = new Document();
        PdfPTable tabla_gastos = new PdfPTable(4);
        Vista_Emitir_Boleta vis = new Vista_Emitir_Boleta();
        String path = "C:\\Users\\tomas\\Desktop\\gastos.pdf";
        try {
            String descuento = "";
            PdfWriter.getInstance(doc_gastos, new FileOutputStream(path));
            doc_gastos.open();
            PreparedStatement ps = null;
            ResultSet rs = null;
            String sql = "SELECT ci.id_compra_insumos, ci.fecha, p.nombre_proveedor, sum(cde.total) from comprar_insumos ci inner join proveedor p on ci.id_proveedor = p.id_proveedor inner join compra_detalle cde on cde.id_comprar_insumos = ci.id_compra_insumos group by ci.id_compra_insumos;";
            ps = cn.prepareStatement(sql);
            rs = ps.executeQuery();
            tabla_gastos.addCell("ID");
            tabla_gastos.addCell("FECHA COMPRA");
            tabla_gastos.addCell("NOMBRE PROVEEDOR");
            tabla_gastos.addCell("TOTAL COMPRA");
            while(rs.next()){
                tabla_gastos.addCell(rs.getString(1));
                tabla_gastos.addCell(rs.getString(2));
                tabla_gastos.addCell(rs.getString(3));
                tabla_gastos.addCell(rs.getString(4));
            }
            String sql1 = "select sum(cde.total) from compra_detalle cde inner join comprar_insumos ci on ci.id_compra_insumos = cde.id_comprar_insumos;";
            ps = cn.prepareStatement(sql1);
            rs = ps.executeQuery();
            if(rs.next()){
               descuento = rs.getString("sum(cde.total)"); 
            }
            Phrase nombre_REST = new Phrase("RESTAURANT SIGLO XXI\n\n\n");
            Phrase fecha = new Phrase("Con fecha: " + vis.fechaActual() + "\n\n");
            Phrase descuentos = new Phrase("Total de compras: " + descuento);
            doc_gastos.add(nombre_REST);
            doc_gastos.add(fecha); 
            doc_gastos.add(tabla_gastos);
            doc_gastos.add(descuentos);
            doc_gastos.close();
            JOptionPane.showMessageDialog(this,"¡Documento generado con éxito!","Aviso",JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(this,"La ruta de su archivo es \n" + path,"Aviso",JOptionPane.INFORMATION_MESSAGE);
        } catch (DocumentException | FileNotFoundException | SQLException e) {
        }
    }//GEN-LAST:event_btnGastosActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnGastos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
